services:  
  ollama:
    restart: always
    volumes:
      - ../volumes/ollama:/root/.ollama
    build:
      context: ../infrastructure/ollama
      dockerfile: Dockerfile
    image: openrag_ollama
    container_name: ${ollama_LOCAL_CONTAINER_NAME}
    pull_policy: always
    tty: true
    environment:
      OLLAMA_MAX_LOADED_MODELS: 5
      OLLAMA_NUM_PARALLEL: 10
      OLLAMA_ORIGINS: "*"
      OLLAMA_KEEP_ALIVE: "60m"
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_LOCAL_VERSION}
    container_name: ${ES_LOCAL_CONTAINER_NAME}
    volumes:
      - ../volumes/dev-elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ES_LOCAL_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.ml.use_auto_machine_memory_percent=true
      - ES_JAVA_OPTS=-Xms${ES_LOCAL_HEAP_INIT} -Xmx${ES_LOCAL_HEAP_MAX}
      - cluster.routing.allocation.disk.watermark.low=${ES_LOCAL_DISK_SPACE_REQUIRED}
      - cluster.routing.allocation.disk.watermark.high=${ES_LOCAL_DISK_SPACE_REQUIRED}
      - cluster.routing.allocation.disk.watermark.flood_stage=${ES_LOCAL_DISK_SPACE_REQUIRED}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --output /dev/null --silent --head --fail -u elastic:${ES_LOCAL_PASSWORD} http://elasticsearch:${ES_LOCAL_PORT}",
        ]
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - app-network
  front:
    build:
      context: ..
      dockerfile: Dockerfile
    image: openrag_front
    container_name: ${FRONT_LOCAL_CONTAINER_NAME}
    ports:
      - "${FRONT_LOCAL_PORT}:8501"
    depends_on:
      - "elasticsearch"   
      - "ollama" 
    networks:
      - app-network
    volumes:
      - ../storage:/app/storage
      - ../data:/app/data
      - ../streamlit_:/app/streamlit_
networks:
  app-network: